_target_: lightning.pytorch.Trainer

default_root_dir: ${paths.trainer}
max_epochs: 999
accelerator: auto
devices: auto
gradient_clip_val: 10
precision: 32
check_val_every_n_epoch: 1
enable_progress_bar: True
# profiler: simple
fast_dev_run: False
